### ISSUE TITLE
Kong v3 breaks rancher setup

### ISSUE THREAD

**Issue by samvdb** [Kong/docker-kong#130]
Note: Not sure how to debug this issue, any suggestions are welcome.

Kong v3 now uses openresty to function. Using the docker files provied here in alpine folder i am not able to get it up and running in a rancher environment.

Apart from the fact that rancher only support v2 for docker-compose file. This can be circumvented by removing the new healthcheck syntax.
Proceeding further i cannot get the container up and running since openresty does not provide any output.

I have tried 2 method to get it working again:

## Compile custom docker image including nginx/kong
Note: I am not sure but container pilot does not seem needed to get this up and running.

```docker
# a minimal Nginx container including ContainerPilot and a simple virtulhost config
FROM nginx:latest

RUN apt-get update && apt-get install -y curl unzip wget tar ca-certificates openssl libpcre3 procps perl

# we use consul-template to re-write our Nginx virtualhost config
RUN curl -Lo /tmp/consul_template_0.14.0_linux_amd64.zip https://releases.hashicorp.com/consul-template/0.14.0/consul-template_0.14.0_linux_amd64.zip && \
    unzip /tmp/consul_template_0.14.0_linux_amd64.zip && \
    mv consul-template /bin


COPY reload-nginx.sh /bin/reload-nginx.sh

# add Nginx virtualhost configuration
COPY nginx.conf /etc/nginx/nginx.conf

# add Nginx virtualhost template that we'll overwrite
COPY nginx.conf.ctmpl /etc/containerpilot/nginx.conf.ctmpl

EXPOSE 8000 8443 8001 8444
ENV KONG_VERSION 0.11.2
ENV KONG_SHA256 10f7f0f5d1bf52afaaf9278f2ef8f7867fec6eb1ce2273ebe6032fa976496011

RUN wget -O kong.deb "https://bintray.com/kong/kong-community-edition-deb/download_file?file_path=kong-community-edition-$KONG_VERSION.stretch.all.deb" \
	&& dpkg -i kong.deb

COPY docker-entrypoint.sh /docker-entrypoint.sh
ENTRYPOINT ["/docker-entrypoint.sh"]

EXPOSE 8000 8443 8001 8444

STOPSIGNAL SIGTERM

CMD ["/usr/local/openresty/nginx/sbin/nginx", "-c", "/usr/local/kong/nginx.conf", "-p", "/usr/local/kong/"]
```

### Output

#kong
<nothing happens>

# Custom docker-compose

Note: Kong migrations and kong refuse to start.

```yaml
version: '2'
services:
  kong:
    image: kong:0.11.2
    container_name: kong
    depends_on:
      - kong-migration
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database

  kong-migration:
    image: kong:0.11.2
    container_name: kong-migration
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
    command: sh -c "kong migrations up && touch migrations_run && sleep 30"

  kong-database:
    image: postgres:9.4-alpine
    container_name: kong-database
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong

  kong-dashboard:
    image: pgb/kong-dashboard:latest
    container_name: kong-dashboard
    depends_on:
      - kong
    entrypoint: ./docker/entrypoint_dev.sh
```

## Output:

No error logs since the containers get killed right after start.

Any help is greatly appreciated in this matter!
I believe i am missing something about openresty and that causes the kong script to return a wrong exit signal.

Thanks
