### ISSUE TITLE
[Docker] KONG ADMIN API not visible by default

### ISSUE THREAD

**Issue by sir-gon** [Kong/docker-kong#140]
Today I made the upgrade from 0.11.2 to 0.12.0

My kong-based platform crash because ADMIN API was unavailable.

As I have enabled the start of KONG in verbose mode, I saw this in my KONG container log:
```
kong_1       | 2018/01/30 15:41:39 [debug] admin_listen = "127.0.0.1:8001"
kong_1       | 2018/01/30 15:41:39 [debug] admin_listen_ssl = "127.0.0.1:8444"
```

Therefore, it was obvious to me that the "admin API" is not exposed by default outside the container (only response from "localhost" or "127.0.0.1" from inside inside). This is the default behavior in 0.12.x ?

This was my **docker-compose.yml** block:

```
  kong:
    build: ./docker/kong
    restart: always
    command: kong start --vv
    networks:
      - webgateway
    #container_name: kong
    depends_on:
      - cassandra
    ports:
      - 80:8000
      - 8443:8443
      - 8001:8001
    volumes:
      - ./docker/kong/nginx:/usr/local/kong/custom
    environment:
      - KONG_DATABASE=cassandra
      - KONG_CASSANDRA_CONTACT_POINTS=cassandra
      - KONG_PG_HOST=cassandra
```

As workaround, I have added my own custom configuration file like this:

**docker-compose.yml**:

```
  kong:
    build: ./docker/kong
    restart: always
    command: sh -c "waitforit -host=cassandra -port=9042 -timeout=9999 -debug && kong start --vv -c /usr/local/kong/custom/nginx-kong.conf"
    networks:
      - webgateway
    #container_name: kong
    depends_on:
      - cassandra
    ports:
      - 80:8000
      - 8443:8443
      - 8001:8001
    volumes:
      - ./docker/kong/nginx:/usr/local/kong/custom
    environment:
      - KONG_DATABASE=cassandra
      - KONG_CASSANDRA_CONTACT_POINTS=cassandra
      - KONG_PG_HOST=cassandra
```

And **./docker/kong/nginx/nginx-kong.conf**:

```
admin_listen = 0.0.0.0:8001
admin_listen_ssl = 0.0.0.0:8444
```

I hope this help, but ... this is some undocumented thing in [Docker Installation](https://getkong.org/install/docker/)?

**Comment by salazar** [comment]
Hi @sir-gon, this is indeed the expected behavior; check out the changelog for 0.12.0 [here](https://github.com/Kong/kong/blob/master/CHANGELOG.md#admin-api). By the way, our Docker Compose file contains the needed [change]( https://github.com/Kong/docker-kong/blob/master/compose/docker-compose.yml#L78), which you could add to your compose file as well! Thank you for taking the time to report this - closing it now.

**Comment by alexsorokoletov** [comment]
this was the crucial stopper for us to deploy to swarm. The environment fix in the compose or the config fix works nice and after that everything is in good shape

Example docker swarm compose file:
```
version: '3.3'

services:
  cassandra:
    deploy:
      replicas: 1 # cassandra has 2 minute rule - scale after 2 minutes of topology change
    entrypoint:
    - "sh"
    - "-c"
    - export CASSANDRA_SEEDS=$$(nrOfTasks=`getent hosts tasks.cassandra | wc -l` ;
      many=`getent hosts tasks.cassandra | awk '{print $$1}' | sed "/$$(hostname --ip-address)/d"
      | paste -d, -s -` ; printf '%s' $$( [ $${nrOfTasks} -gt 1 ] && echo $${many} ||
      echo "$$(hostname --ip-address)" )) ; /docker-entrypoint.sh cassandra -f
    environment:
      HEAP_NEWSIZE: 256M
      MAX_HEAP_SIZE: 768M
    image: cassandra
    networks:
      - internal

  kong-migration:
    image: kong
    environment:
      - KONG_DATABASE=cassandra
      - KONG_CASSANDRA_CONTACT_POINTS=tasks.kong_cassandra
    command: kong migrations up
    networks:
      - internal
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure # so that it works only once to do the migrations

  kong:
    image: kong
    environment:
      - KONG_DATABASE=cassandra
      - KONG_CASSANDRA_CONTACT_POINTS=tasks.kong_cassandra
      - KONG_MEM_CACHE_SIZE=32M
      - KONG_ADMIN_LISTEN=0.0.0.0:8001 # this is THE LINE
    ports:
      - 10000:8000
      - 10001:8001
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - traefik.frontend.rule=Host:yourpublic.domain.com
        - traefik.docker.network=traefik_public
        - traefik.port=8000            
    networks:
      - internal
      - traefik_public

  kong-dashboard: 
    image: pgbi/kong-dashboard
    ports:
      - 7080:8080
    command: start --kong-url http://tasks.kong_kong:8001
    networks:
      - internal
      - traefik_public
    deploy:
      mode: replicated
      replicas: 0
      labels:
        - traefik.frontend.rule=Host:youradmin.domain.com
        - traefik.docker.network=traefik_public
        - traefik.port=8080

networks:
  traefik_public:
    external: true
  internal:
    driver: overlay
```
