### ISSUE TITLE
How to load plugins and create APIs automatically on Kong startup?

### ISSUE THREAD

**Issue by jCalamari** [Kong/docker-kong#150]
Is there a way to configure the image to start with preconfigured APIs/plugins? Currently, I've got just another docker container with bunch of curls:

```
  kong-apis:
    container_name: kong-apis
    image: 'kong:0.12.3'
    command:
      bash -c "curl -s -L -XPOST http://kong:8001/apis --data ..."
    depends_on:
      kong:
        condition: service_healthy
```
