### ISSUE TITLE
Problem using docker-kong via docker run, but works correctly via docker-compose

### ISSUE THREAD

**Issue by cewood** [Kong/docker-kong#305]
The `docker-compose` config below works as expected

```
version: '2.1'

services:
  kong:
    image: "kong:1.4.0-alpine"
    environment:
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: '0.0.0.0:8001'
      KONG_DATABASE: 'off'
      KONG_LOG_LEVEL: info
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
    ports:
      - "8000:8000/tcp"
      - "8001:8001/tcp"
      - "8443:8443/tcp"
      - "8444:8444/tcp"
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: on-failure
```

however this equivalent `docker run` command does not:

```
docker run --rm -it \
  -e KONG_ADMIN_ACCESS_LOG=/dev/stdout \
  -e KONG_ADMIN_ERROR_LOG=/dev/stderr \
  -e KONG_ADMIN_LISTEN=0.0.0.0:8001 \
  -e KONG_DATABASE=off \
  -e KONG_LOG_LEVEL=info \
  -e KONG_PROXY_ACCESS_LOG=/dev/stdout \
  -e KONG_PROXY_ERROR_LOG=/dev/stderr \
  -p 8000:8000/tcp \
  -p 8001:8001/tcp \
  -p 8443:8443/tcp \
  -p 8444:8444/tcp \
  kong:1.4.0-alpine
```

Is there any reason this should be the case, or is this a bug?
