### ISSUE TITLE
Docker-compose file doesn't work

### ISSUE THREAD

**Issue by ridvanaltun** [Kong/docker-kong#351]
Last changes effect docker-compose file.  When this morning `docker-compose up` worked fine but now it is not working.

I tested lastest release (2.0.2) on my computer, it is working.

**<details><summary>Click to see output</summary>**

```
WARNING: Some services (db, kong, kong-migrations, kong-migrations-up) use the 'deploy' key, which will be ignored. Compose does not support 'deploy' configuration - use `docker stack deploy` to deploy to a swarm.
Creating network "compose_kong-net" with the default driver
Creating compose_db_1 ... done
Creating compose_kong-migrations-up_1 ... done
Creating compose_kong_1               ... done
Creating compose_kong-migrations_1    ... done
Attaching to compose_db_1, compose_kong-migrations-up_1, compose_kong-migrations_1, compose_kong_1
db_1                  |
db_1                  | PostgreSQL Database directory appears to contain a database; Skipping initialization
db_1                  |
db_1                  | LOG:  database system was shut down at 2020-03-19 18:28:54 UTC
db_1                  | LOG:  MultiXact member wraparound protections are now enabled
db_1                  | LOG:  autovacuum launcher started
db_1                  | LOG:  database system is ready to accept connections
kong-migrations-up_1  | Error: missing password, required for connect
kong-migrations-up_1  |
kong-migrations-up_1  |   Run with --v (verbose) or --vv (debug) for more details
kong-migrations_1     | Error: missing password, required for connect
kong-migrations_1     |
kong-migrations_1     |   Run with --v (verbose) or --vv (debug) for more details
kong_1                | 2020/03/19 18:30:06 [error] 1#0: init_by_lua error: /usr/local/share/lua/5.1/pgmoon/init.lua:271: missing password, required for connect
kong_1                | stack traceback:
kong_1                |         [C]: in function 'assert'
kong_1                |         /usr/local/share/lua/5.1/pgmoon/init.lua:271: in function 'auth'
kong_1                |         /usr/local/share/lua/5.1/pgmoon/init.lua:211: in function 'connect'
kong_1                |         .../share/lua/5.1/kong/db/strategies/postgres/connector.lua:202: in function 'connect'
kong_1                |         .../share/lua/5.1/kong/db/strategies/postgres/connector.lua:489: in function 'query'
kong_1                |         .../share/lua/5.1/kong/db/strategies/postgres/connector.lua:270: in function 'init'
kong_1                |         /usr/local/share/lua/5.1/kong/db/init.lua:138: in function 'init_connector'
kong_1                |         /usr/local/share/lua/5.1/kong/init.lua:389: in function 'init'
kong_1                |         init_by_lua:3: in main chunk
kong_1                | nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/pgmoon/init.lua:271: missing password, required for connect
kong_1                | stack traceback:
kong_1                |         [C]: in function 'assert'
kong_1                |         /usr/local/share/lua/5.1/pgmoon/init.lua:271: in function 'auth'
kong_1                |         /usr/local/share/lua/5.1/pgmoon/init.lua:211: in function 'connect'
kong_1                |         .../share/lua/5.1/kong/db/strategies/postgres/connector.lua:202: in function 'connect'
kong_1                |         .../share/lua/5.1/kong/db/strategies/postgres/connector.lua:489: in function 'query'
kong_1                |         .../share/lua/5.1/kong/db/strategies/postgres/connector.lua:270: in function 'init'
kong_1                |         /usr/local/share/lua/5.1/kong/db/init.lua:138: in function 'init_connector'
kong_1                |         /usr/local/share/lua/5.1/kong/init.lua:389: in function 'init'
kong_1                |         init_by_lua:3: in main chunk
compose_kong-migrations-up_1 exited with code 1
compose_kong-migrations_1 exited with code 1
kong-migrations-up_1  | Error: missing password, required for connect
kong-migrations-up_1  |
kong-migrations-up_1  |   Run with --v (verbose) or --vv (debug) for more details
compose_kong_1 exited with code 1
kong-migrations_1     | Error: missing password, required for connect
kong-migrations_1     |
kong-migrations_1     |   Run with --v (verbose) or --vv (debug) for more details
kong_1                | 2020/03/19 18:30:09 [error] 1#0: init_by_lua error: /usr/local/share/lua/5.1/pgmoon/init.lua:271: missing password, required for connect
kong_1                | stack traceback:
kong_1                |         [C]: in function 'assert'
kong_1                |         /usr/local/share/lua/5.1/pgmoon/init.lua:271: in function 'auth'
kong_1                |         /usr/local/share/lua/5.1/pgmoon/init.lua:211: in function 'connect'
kong_1                |         .../share/lua/5.1/kong/db/strategies/postgres/connector.lua:202: in function 'connect'
kong_1                |         .../share/lua/5.1/kong/db/strategies/postgres/connector.lua:489: in function 'query'
kong_1                |         .../share/lua/5.1/kong/db/strategies/postgres/connector.lua:270: in function 'init'
kong_1                |         /usr/local/share/lua/5.1/kong/db/init.lua:138: in function 'init_connector'
kong_1                |         /usr/local/share/lua/5.1/kong/init.lua:389: in function 'init'
kong_1                |         init_by_lua:3: in main chunk
kong_1                | nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/pgmoon/init.lua:271: missing password, required for connect
kong_1                | stack traceback:
kong_1                |         [C]: in function 'assert'
kong_1                |         /usr/local/share/lua/5.1/pgmoon/init.lua:271: in function 'auth'
kong_1                |         /usr/local/share/lua/5.1/pgmoon/init.lua:211: in function 'connect'
kong_1                |         .../share/lua/5.1/kong/db/strategies/postgres/connector.lua:202: in function 'connect'
kong_1                |         .../share/lua/5.1/kong/db/strategies/postgres/connector.lua:489: in function 'query'
kong_1                |         .../share/lua/5.1/kong/db/strategies/postgres/connector.lua:270: in function 'init'
kong_1                |         /usr/local/share/lua/5.1/kong/db/init.lua:138: in function 'init_connector'
kong_1                |         /usr/local/share/lua/5.1/kong/init.lua:389: in function 'init'
kong_1                |         init_by_lua:3: in main chunk
kong-migrations-up_1  | Error: missing password, required for connect
kong-migrations-up_1  |
kong-migrations-up_1  |   Run with --v (verbose) or --vv (debug) for more details
Exception in thread Thread-13:
Traceback (most recent call last):
  File "site-packages/docker/api/client.py", line 261, in _raise_for_status
  File "site-packages/requests/models.py", line 940, in raise_for_status
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: http://127.0.0.1:2375/v1.38/containers/6adf378e93c3350f9ef9e3ba22326430f13c85a4dc74865f7370b3a17038b586/attach?logs=0&stdout=1&stderr=1&stream=1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 916, in _bootstrap_inner
  File "threading.py", line 864, in run
  File "compose/cli/log_printer.py", line 233, in watch_events
  File "compose/container.py", line 215, in attach_log_stream
  File "compose/container.py", line 307, in attach
  File "site-packages/docker/utils/decorators.py", line 19, in wrapped
  File "site-packages/docker/api/container.py", line 61, in attach
  File "site-packages/docker/api/client.py", line 400, in _read_from_socket
  File "site-packages/docker/api/client.py", line 311, in _get_raw_response_socket
  File "site-packages/docker/api/client.py", line 263, in _raise_for_status
  File "site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
docker.errors.APIError: 409 Client Error: Conflict ("b'container 6adf378e93c3350f9ef9e3ba22326430f13c85a4dc74865f7370b3a17038b586 is restarting, wait until the container is running'")

kong-migrations_1     | Error: missing password, required for connect
kong-migrations_1     |
kong-migrations_1     |   Run with --v (verbose) or --vv (debug) for more details
compose_kong-migrations-up_1 exited with code 1
compose_kong-migrations_1 exited with code 1
compose_kong_1 exited with code 1
compose_kong-migrations-up_1 exited with code 1
compose_kong-migrations_1 exited with code 1
```
</details>

**Comment by rfmarks** [comment]
Got same issue here.. seems there's a missing `docker-entrypoint.sh` strategy for the compose.. I could not find how the env `KONG_PG_PASSWORD_FILE` would become `KONG_PG_PASSWORD` without it

**Comment by 0x6B386F** [comment]
Same here. 

Workaround:

```yaml
version: '3.7'

volumes:
  kong_data: {}

networks:
  kong-net:
    external: false

secrets:
  kong_postgres_password:
    file: ./POSTGRES_PASSWORD

services:
  kong-migrations:
    image: "${KONG_DOCKER_TAG:-kong:latest}"
    command: kong migrations bootstrap
    depends_on:
      - db
    environment:
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: ${KONG_PG_DATABASE:-kong}
      KONG_PG_HOST: db
      KONG_PG_USER: ${KONG_PG_USER:-kong}
      KONG_PG_PASSWORD: password
      #KONG_PG_PASSWORD_FILE: /run/secrets/kong_postgres_password
    secrets:
      - kong_postgres_password
    networks:
      - kong-net
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure

  kong-migrations-up:
    image: "${KONG_DOCKER_TAG:-kong:latest}"
    command: kong migrations up && kong migrations finish
    depends_on:
      - db
    environment:
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: ${KONG_PG_DATABASE:-kong}
      KONG_PG_HOST: db
      KONG_PG_USER: ${KONG_PG_USER:-kong}
      KONG_PG_PASSWORD: password
      #KONG_PG_PASSWORD_FILE: /run/secrets/kong_postgres_password
    secrets:
      - kong_postgres_password
    networks:
      - kong-net
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure

  kong:
    image: "${KONG_DOCKER_TAG:-kong:latest}"
    user: "${KONG_USER:-kong}"
    depends_on:
      - db
    environment:
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: '0.0.0.0:8001'
      KONG_CASSANDRA_CONTACT_POINTS: db
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: ${KONG_PG_DATABASE:-kong}
      KONG_PG_HOST: db
      KONG_PG_USER: ${KONG_PG_USER:-kong}
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_PG_PASSWORD: password
      #KONG_PG_PASSWORD_FILE: /run/secrets/kong_postgres_password
    secrets:
      - kong_postgres_password
    networks:
      - kong-net
    ports:
      - "8000:8000/tcp"
      - "127.0.0.1:8001:8001/tcp"
      - "8443:8443/tcp"
      - "127.0.0.1:8444:8444/tcp"
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure

  db:
    image: postgres:9.5
    environment:
      POSTGRES_DB: ${KONG_PG_DATABASE:-kong}
      POSTGRES_USER: ${KONG_PG_USER:-kong}
      POSTGRES_PASSWORD_FILE: /run/secrets/kong_postgres_password
    secrets:
      - kong_postgres_password
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${KONG_PG_USER:-kong}"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
    stdin_open: true
    tty: true
    networks:
      - kong-net
    volumes:
      - kong_data:/var/lib/postgresql/data

```
