### ISSUE TITLE
2.1 beta 1:  missing database for connect

### ISSUE THREAD

**Issue by luispabon** [Kong/docker-kong#379]
```
nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/pgmoon/init.lua:550: missing database for connect
stack traceback:
	[C]: in function 'assert'
	/usr/local/share/lua/5.1/pgmoon/init.lua:550: in function 'send_startup_message'
	/usr/local/share/lua/5.1/pgmoon/init.lua:207: in function 'connect'
	.../share/lua/5.1/kong/db/strategies/postgres/connector.lua:211: in function 'connect'
	.../share/lua/5.1/kong/db/strategies/postgres/connector.lua:527: in function 'query'
	.../share/lua/5.1/kong/db/strategies/postgres/connector.lua:279: in function 'init'
	/usr/local/share/lua/5.1/kong/db/init.lua:139: in function 'init_connector'
	/usr/local/share/lua/5.1/kong/init.lua:419: in function 'init'
	init_by_lua:3: in main chunk
```

This is happening with the normal and alpine versions of the image. Weirdly enough, it does not happen with the migrations:

kong migrations up:
```
migrating core on database 'kong'...
core migrated up to: 009_200_to_210 (pending)
migrating rate-limiting on database 'kong'...
rate-limiting migrated up to: 004_200_to_210 (executed)
migrating hmac-auth on database 'kong'...
hmac-auth migrated up to: 003_200_to_210 (pending)
migrating oauth2 on database 'kong'...
oauth2 migrated up to: 004_200_to_210 (pending)
migrating ip-restriction on database 'kong'...
ip-restriction migrated up to: 001_200_to_210 (pending)
migrating jwt on database 'kong'...
jwt migrated up to: 003_200_to_210 (pending)
migrating basic-auth on database 'kong'...
basic-auth migrated up to: 003_200_to_210 (pending)
migrating key-auth on database 'kong'...
key-auth migrated up to: 003_200_to_210 (pending)
migrating acl on database 'kong'...
acl migrated up to: 003_200_to_210 (pending)
migrating bot-detection on database 'kong'...
bot-detection migrated up to: 001_200_to_210 (pending)
10 migrations processed
1 executed
9 pending
```

kong migrations finish
```
migrating core on database 'kong'...
core migrated up to: 009_200_to_210 (executed)
migrating hmac-auth on database 'kong'...
hmac-auth migrated up to: 003_200_to_210 (executed)
migrating oauth2 on database 'kong'...
oauth2 migrated up to: 004_200_to_210 (executed)
migrating ip-restriction on database 'kong'...
ip-restriction migrated up to: 001_200_to_210 (executed)
migrating jwt on database 'kong'...
jwt migrated up to: 003_200_to_210 (executed)
migrating basic-auth on database 'kong'...
basic-auth migrated up to: 003_200_to_210 (executed)
migrating key-auth on database 'kong'...
key-auth migrated up to: 003_200_to_210 (executed)
migrating acl on database 'kong'...
acl migrated up to: 003_200_to_210 (executed)
migrating bot-detection on database 'kong'...
bot-detection migrated up to: 001_200_to_210 (executed)
9 migrations processed
9 executed
No pending migrations to finish
```

The container configuration is the same, using the same environment variables to configure for a PostgreSQL 9.6 CloudSQL instance in Google Cloud.

The exact same kubernetes deployment works correctly on `kong:2.0`

**Comment by hutchic** [comment]
can you provide the deployment YAML?

**Comment by luispabon** [comment]
Of course:

```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kong
  namespace: gateway
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      name: kong-daemonset
  template:
    metadata:
      labels:
        name: kong-daemonset
        app: kong
    spec:
      containers:
      # SSL redirect - http>https connection upgrades
      - name: ssl-redirect
        image: phpdockerio/ssl-redirect:1.0.0

        ports:
          - name: http
            containerPort: 80
            protocol: TCP

      # Kong instance
      - name: kong
        image: library/kong:2.1-alpine

        env:
          # This fixes tty issues when opening a shell
          - name: TERM
            value: linux

          - name: KONG_DATABASE
            value: postgres

          - name: KONG_PROXY_ERROR_LOG
            value: /dev/stderr

          - name: KONG_PROXY_ACCESS_LOG
            value: /dev/stdout

          - name: KONG_ADMIN_ERROR_LOG
            value: /dev/stderr

          - name: KONG_ADMIN_ACCESS_LOG
            value: /dev/stdout

          - name: KONG_ADMIN_LISTEN
            value: 0.0.0.0:8001

          - name: KONG_PG_HOST
            valueFrom:
              secretKeyRef:
                name: kong-config
                key: db.host

          - name: KONG_PG_USER
            valueFrom:
              secretKeyRef:
                name: kong-config
                key: db.user

          - name: KONG_PG_PASSWORD
            valueFrom:
              secretKeyRef:
                name: kong-config
                key: db.passwd

          - name: POD_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP

          - name: KONG_CLUSTER_ADVERTISE
            value: $(POD_IP):7946

        ports:
        # For admin API
        - name: admin
          containerPort: 8001
          protocol: TCP

        # These are the actual HTTP endpoints we expose to the world
        - name: proxy
          containerPort: 8000
          protocol: TCP
        - name: proxy-ssl
          containerPort: 8443
          protocol: TCP

        # Internal kong clustering ports
        - name: surf-tcp
          containerPort: 7946
          protocol: TCP
        - name: surf-udp
          containerPort: 7946
          protocol: UDP
```

Migrations up/down:

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: kong-migration-start
  namespace: gateway
spec:
  template:
    spec:
      containers:
      - name: migration-start
        image: library/kong:2.1-alpine
        command: [ "kong", "migrations", "up" ]
        env:
          - name: KONG_DATABASE
            value: postgres

          - name: KONG_PG_HOST
            valueFrom:
              secretKeyRef:
                name: kong-config
                key: db.host

          - name: KONG_PG_USER
            valueFrom:
              secretKeyRef:
                name: kong-config
                key: db.user

          - name: KONG_PG_PASSWORD
            valueFrom:
              secretKeyRef:
                name: kong-config
                key: db.passwd
      restartPolicy: Never
  backoffLimit: 4

```

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: kong-migration-finish
  namespace: gateway
spec:
  template:
    spec:
      containers:
      - name: migration-start
        image: library/kong:2.1-alpine
        command: [ "kong", "migrations", "finish" ]
        env:
          - name: KONG_DATABASE
            value: postgres

          - name: KONG_PG_HOST
            valueFrom:
              secretKeyRef:
                name: kong-config
                key: db.host

          - name: KONG_PG_USER
            valueFrom:
              secretKeyRef:
                name: kong-config
                key: db.user

          - name: KONG_PG_PASSWORD
            valueFrom:
              secretKeyRef:
                name: kong-config
                key: db.passwd
      restartPolicy: Never
  backoffLimit: 4
```

**Comment by ivangfr** [comment]
I am facing a similar problem when running the migration (log below)...

Here is the project (https://github.com/ivangfr/springboot-kong) I am trying to upgrade `Kong` from `2.0.4` to `2.1.0-beta.1`.

It has a script that starts all Docker containers (https://github.com/ivangfr/springboot-kong/blob/master/start-docker-containers.sh). In it, please, replace `kong:2.0.4` to `kong:2.1.0-beta.1`.

---
```
$ docker run --rm \
  --network=springboot-kong-net \
  -e "KONG_DATABASE=postgres" \
  -e "KONG_PG_HOST=kong-database" \
  -e "KONG_PG_PASSWORD=kong" \
  kong:2.1.0-beta.1 kong migrations bootstrap -v
Running kong-database migration
2020/07/03 15:42:31 [verbose] Kong: 2.1.0beta.1
Error:
/usr/local/share/lua/5.1/pgmoon/init.lua:550: missing database for connect
stack traceback:
	[C]: in function 'assert'
	/usr/local/share/lua/5.1/pgmoon/init.lua:550: in function 'send_startup_message'
	/usr/local/share/lua/5.1/pgmoon/init.lua:207: in function 'connect'
	.../share/lua/5.1/kong/db/strategies/postgres/connector.lua:211: in function 'connect'
	.../share/lua/5.1/kong/db/strategies/postgres/connector.lua:527: in function 'query'
	.../share/lua/5.1/kong/db/strategies/postgres/connector.lua:279: in function 'init'
	/usr/local/share/lua/5.1/kong/db/init.lua:139: in function 'init_connector'
	/usr/local/share/lua/5.1/kong/cmd/migrations.lua:95: in function 'cmd_exec'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:88>
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:45>
	/usr/local/bin/kong:9: in function 'file_gen'
	init_worker_by_lua:48: in function <init_worker_by_lua:46>
	[C]: in function 'xpcall'
	init_worker_by_lua:55: in function <init_worker_by_lua:53>
2020/07/03 15:42:31 [verbose] no config file found at /etc/kong/kong.conf
2020/07/03 15:42:31 [verbose] no config file found at /etc/kong.conf
2020/07/03 15:42:31 [verbose] no config file, skip loading
2020/07/03 15:42:31 [verbose] prefix in use: /usr/local/kong
```

**Comment by joaonsantos** [comment]
This also happens for us. `missing database for connect`

Deployment YAML
```
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: kong-dev
  labels:
    app: kong
spec:
  type: NodePort
  ports:
    - name: traffic
      port: 8000
      protocol: TCP
    - name: admin
      port: 8001    
      protocol: TCP
  selector:
    app: kong
    service: gateway
---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: kong-dev
spec:
  replicas: 0
  selector:
    matchLabels:
      app: kong
      service: gateway
  template:
    metadata:
      labels:
        app: kong
        service: gateway
    spec:
      containers:
      - image: kong:2.0
        name: gateway
        env:
          - name: KONG_PG_HOST
            value: postgres
          - name: KONG_DATABASE
            value: "postgres"
          - name: KONG_PG_USER
            value: "kong"
          - name: KONG_PG_PASSWORD
            value: "kong"
          - name: KONG_PROXY_ACCESS_LOG
            value: /dev/stdout
          - name: KONG_ADMIN_ACCESS_LOG
            value: /dev/stdout
          - name: KONG_PROXY_ERROR_LOG
            value: /dev/stdout
          - name: KONG_ADMIN_ERROR_LOG
            value: /dev/stdout
          - name: KONG_ADMIN_LISTEN
            value: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
        ports:
          - containerPort: 8000
          - containerPort: 8443
          - containerPort: 8001
          - containerPort: 8444
      initContainers:
        - name: init-postgres
          image: busybox:latest
          command: ['sh', '-c', "until nslookup postgres.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for postgres; sleep 2; done"]
          
---
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: kong-dev
  labels:
    app: kong
spec:
  type: NodePort
  ports:
    - port: 5432
      name: http
  selector:
    app: kong
    service: postgres
---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: kong-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong
      service: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kong
        service: postgres
    spec:
      containers:
        - image: postgres:12
          name: postgres
          env:
            - name: POSTGRES_DB
              value: "kong"
            - name: POSTGRES_USER
              value: "kong"
            - name: POSTGRES_PASSWORD
              value: "kong"
          ports:
            - containerPort: 5432
---
---
apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
  namespace: kong-dev
spec:
  template:
    spec:
      containers:
      - name: db-migration
        image: kong:2.1
        env:
          - name: KONG_DATABASE
            value: "postgres"
          - name: KONG_PG_HOST
            value: postgres
          - name: KONG_PG_USER
            value: "kong"
          - name: KONG_PG_PASSWORD
            value: "kong"
        command: ['sh', '-c', "kong migrations bootstrap"]
      initContainers:
        - name: init-postgres
          image: busybox:latest
          command: ['sh', '-c', "until nslookup postgres.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for postgres; sleep 2; done"]
      restartPolicy: Never
  backoffLimit: 4
```
