### ISSUE TITLE
Chained migration commands in docker-compose not working with kong 2.1.0

### ISSUE THREAD

**Issue by dlouzan** [Kong/docker-kong#398]
We have a custom docker-compose adapted from the official compose file at https://github.com/Kong/docker-kong/blob/master/compose/docker-compose.yml, and with the latest kong 2.1.0 docker image we are having issues chaining multiple migration commands via `&&`, only the first command is executed, and the rest are ignored.

We are wondering if the entry point was somehow modified (but undocumented in the changelog and migration docs) and that makes it not work properly. AFAIK the default image is alpine-based and hasn't changed.

This will only execute the first `kong migrations bootstrap` and exit with status `0`, the `up` & `finish` will not be executed:

```yaml
  kong-migrations:
    image: kong:2.1.0
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: xxx
    command: kong migrations bootstrap && kong migrations up && kong migrations finish
    restart: on-failure
    depends_on:
    - kong-database
```

This on the other hand works:

```yaml
  kong-migrations:
    image: kong:2.1.0
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: xxx
    command: >
      sh -c "kong migrations bootstrap &&
             kong migrations up &&
             kong migrations finish"
    restart: on-failure
    depends_on:
    - kong-database
```
