### ISSUE TITLE
Kong error with custom javascript plugin

### ISSUE THREAD

**Issue by davidespihernandez** [Kong/docker-kong#485]
Hi!
We need to implement a custom plugin in javascript. We followed the instructions here:

Plugins in Other Languages - v2.5.x | Kong - Open-Source API Management and Microservice Management
Building a Kong Gateway Plugin with JavaScript - KongHQ
The second page tutorial is not working (docker-compose command fails with the current repo code).
Finally, we came up with this code:

Dockerfile

```
FROM kong:2.5.0-alpine

USER root

RUN apk add --no-cache --update nodejs npm

RUN apk add --no-cache --virtual .gyp python3 make g++ \
    && npm -g config set user $USER && npm install kong-pdk -g \
    && apk del .gyp
```

docker-compose

```
  kong:
    build:
      context: .
      dockerfile: ./Dockerfile
    user: "${KONG_USER:-kong}"
    depends_on:
      - db
    environment:
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_PROXY_LISTEN: "${KONG_PROXY_LISTEN:-0.0.0.0:8000}"
      KONG_ADMIN_LISTEN: "${KONG_ADMIN_LISTEN:-0.0.0.0:8001}"
      KONG_CASSANDRA_CONTACT_POINTS: db
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: ${KONG_PG_DATABASE:-kong}
      KONG_PG_HOST: db
      KONG_PG_USER: ${KONG_PG_USER:-kong}
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_PG_PASSWORD_FILE: /run/secrets/kong_postgres_password
      KONG_PREFIX: ${KONG_PREFIX:-/var/run/kong}
      # Enable the JS plugin server
      KONG_PLUGINSERVER_NAMES: js
      KONG_PLUGINSERVER_JS_SOCKET: /usr/local/kong/js_pluginserver.sock
      KONG_PLUGINSERVER_JS_START_CMD: /usr/bin/kong-js-pluginserver -v --plugins-directory /usr/local/kong/js-plugins
      KONG_PLUGINSERVER_JS_QUERY_CMD: /usr/bin/kong-js-pluginserver --plugins-directory /usr/local/kong/js-plugins --dump-all-plugins
#      # Allow plugins to be used. The plugin name is your JS file name e.g. hello.js
      KONG_PLUGINS: bundled, validator
    secrets:
      - kong_postgres_password
    ports:
      # The following two environment variables default to an insecure value (0.0.0.0)
      # according to the CIS Security test.
      - "${KONG_INBOUND_PROXY_LISTEN:-0.0.0.0}:8000:8000/tcp"
      - "${KONG_INBOUND_SSL_PROXY_LISTEN:-0.0.0.0}:8443:8443/tcp"
      # Making them mandatory but undefined, like so would be backwards-breaking:
      # - "${KONG_INBOUND_PROXY_LISTEN?Missing inbound proxy host}:8000:8000/tcp"
      # - "${KONG_INBOUND_SSL_PROXY_LISTEN?Missing inbound proxy ssl host}:8443:8443/tcp"
      # Alternative is deactivating check 5.13 in the security bench, if we consider Kong's own config to be enough security here

      - "127.0.0.1:8001:8001/tcp"
      - "127.0.0.1:8444:8444/tcp"
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: on-failure:5
    read_only: true
    volumes:
      - kong_prefix_vol:${KONG_PREFIX:-/var/run/kong}
      - kong_tmp_vol:/tmp
      - ./plugins:/usr/local/kong/js-plugins
    deploy:
      restart_policy:
        delay: 50s
        condition: on-failure
        max_attempts: 5
        window: 10s
      resources:
        limits:
          cpus: '2'
          memory: '2g'
    security_opt:
      - no-new-privileges
```

We have a folder called plugins where is located the validator.js file:

```
'use strict';

// This is an example plugin that adds a header to the response

class ValidatorPlugin {
    constructor(config) {
        this.config = config
    }

    async access(kong) {
        let host = await kong.request.getHeader("host")
        if (host === undefined) {
            return await kong.log.err("unable to get header for request")
        }

        let message = this.config.message || "hello"

        // the following can be "parallel"ed
        await Promise.all([
            kong.response.setHeader("x-hello-from-javascript", "Javascript validator says " + message + " to " + host),
        ])
    }
}

module.exports = {
    Plugin: ValidatorPlugin,
    Schema: [
        { message: { type: "string" } },
    ],
    Version: '0.1.0',
    Priority: 0,
}
```

But when the container starts we get this error:

```
kong_1                | 2021/07/26 08:54:37 [notice] 32#0: *17 [kong] process.lua:270 external pluginserver 'js' terminated: exit 1, context: ngx.timer
kong_1                | 2021/07/26 08:54:38 [notice] 32#0: *17 [kong] process.lua:254 Starting js, context: ngx.timer
```

What are we missing?
