### ISSUE TITLE
Kong as daemon

### ISSUE THREAD

**Issue by rncortes1990** [Kong/docker-kong#68]
I'm having issues with the compose version, because the container is always restarting... How do I know if the problem is my machine or the image? Is there any command that can help me printing the error?

Thank you for your time.

PS: I used your compose version without making changes into it. So That is why I'm asking through this platform.

**Comment by c-knowles** [comment]
User of kong here... There's a `nginx_daemon` [setting](https://getkong.org/docs/0.9.x/configuration/) which may help. You should be able to turn that on by setting `KONG_NGINX_DAEMON=on` under `environment` in the docker compose file. Other than that logs seems to go to `/usr/local/kong/logs/` inside the container, which there is an [issue](https://github.com/Mashape/docker-kong/issues/40) for. If the container is restarting quickly it may be hard to access that though so you could mount it as a volume back to your host in the docker compose file.

**Comment by c-knowles** [comment]
Sorry I just noticed `KONG_NGINX_DAEMON` is set in [the entrypoint script](https://github.com/Mashape/docker-kong/blob/master/docker-entrypoint.sh#L5). But the logging part is still valid.

**Comment by chris-fung** [comment]
I'm having the same issue with @rncortes1990 . I'm running kong image on swarm mode, but the problems continues.
  ```YAML
version: "3.1"
services:

  db:
    image: cassandra:3.10
    volumes:
      - db-data:/var/lib/cassandra/data
    networks:
      - mynet
    deploy:
      placement:
        constraints:
          - node.role == manager
          - node.hostname == ubuntu

  kong:
    image: kong:0.10.0
    environment:
      - KONG_DATABASE=cassandra
      - KONG_CASSANDRA_CONTACT_POINTS=db
      - KONG_PG_HOST=db
    networks:
      - mynet
    depends_on:
      - db
    deploy:
      replicas: 2

  nginx:
    image: aaa.bbb/nginx-lb:1.2
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8443:8443"
    networks:
      - mynet
    depends_on:
      - kong
    deploy:
      replicas: 2

  konga:
    image: pantsel/konga:latest
    ports:
      - "1338:1338"
    networks:
      - mynet
    depends_on:
      - nginx
    deploy:
      placement:
        constraints:
          - node.role == manager

networks:
  mynet:
    external:
      name: mynet

volumes:
  db-data:
```
