### ISSUE TITLE
[HELP] Tunnels + Compose

### ISSUE THREAD

**Issue by jd-apprentice** [Kong/docker-kong#704]
Hi! I'm trying to use kong with the new ui, since a 3rd party one (konga) is deprecated, I've been trying to install a fresh one (without taking in consideration my old configuration) but using this docker-compose -> https://github.com/Kong/docker-kong/blob/master/compose/docker-compose.yml

Is not working, either by exposing via NGINX (with port 8002 open) or with cloudflare tunnels.

I get only to this point 

![image](https://github.com/Kong/docker-kong/assets/68082746/e4fce510-e5ac-4c4c-bcb7-66e638019943)

I see that request running on port 8444 are not working

![image](https://github.com/Kong/docker-kong/assets/68082746/67cfbe1d-a1dd-4a8b-8f9a-17c65f12e953)

The only things I've changed from the base docker compose is that I removed the kong-net and leave it in the default one and this part

```yml
  kong:
    image: "${KONG_DOCKER_TAG:-kong:latest}"
    user: "${KONG_USER:-kong}"
    environment:
      <<: *kong-env
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_PROXY_LISTEN: "${KONG_PROXY_LISTEN:-0.0.0.0:8000}"
      KONG_ADMIN_LISTEN: "${KONG_ADMIN_LISTEN:-0.0.0.0:8001}"
      KONG_ADMIN_GUI_LISTEN: "${KONG_ADMIN_GUI_LISTEN:-0.0.0.0:8002}"
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_PREFIX: ${KONG_PREFIX:-/var/run/kong}
      KONG_DECLARATIVE_CONFIG: "/opt/kong/kong.yaml"
    secrets:
      - kong_postgres_password
    ports:
      - "${KONG_INBOUND_PROXY_LISTEN:-192.168.0.219}:8000:8000/tcp"
      - "${KONG_INBOUND_SSL_PROXY_LISTEN:-192.168.0.219}:8443:8443/tcp"
      - "192.168.0.219:8001:8001/tcp"
      - "192.168.0.219:8444:8444/tcp"
      - "192.168.0.219:8002:8002/tcp"
```

The 0.219 IP is my machine since the tunnel is in another server (in the same network)
