### ISSUE TITLE
Kong manager not conneting to kong admin API

### ISSUE THREAD

**Issue by andresmorago** [Kong/docker-kong#719]
Hello everyone,

I'm currently deploying a Docker Compose setup on my server, and I'm facing issues with accessing Kong Manager. It seems like the port mapping in my docker-compose.yml file isn't working correctly.

The primary goal is to access Kong Manager from a remote machine. Kong is running on my server, and I've customized the mapped ports. However, Kong Manager still tries to access port 8001 using my server's external IP instead of routing through Docker.

Here is the error that i see on the web page 

![image](https://github.com/user-attachments/assets/d68a120d-5ba2-4665-85e7-328602bb0f1b)

as well as in the console
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://172.30.19.123:8001/workspaces?size=1000. (Reason: CORS request did not succeed). Status code: (null).`

Here is my current docker-compose.yml
 
```
services:
  kong-database:
    image: postgres:13
    container_name: kong-database
    restart: unless-stopped
    networks:
      - subred_fcv_04
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kongpass
    volumes:
      - ./kong_db:/var/lib/postgresql/data

  kong-gateway:
    image: kong/kong-gateway:3.7.1.2
    container_name: kong-gateway
    restart: unless-stopped
    networks:
      - subred_fcv_01
      - subred_fcv_04
      - subred_fcv_03

    ports:
      - "28000:8000" #Takes incoming HTTP traffic from Consumers, and forwards it to upstream Services.
      - "28002:8002" #Kong Manager (GUI). Listens for HTTP traffic.

    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kongpass
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
#      KONG_ADMIN_GUI_LISTEN: http://0.0.0.0:8002     
      KONG_ADMIN_GUI_URL: http://0.0.0.0:8002
#      KONG_ADMIN_GUI_URL: "*"
#      KONG_ADMIN_GUI_PATH: /

    command: kong migrations bootstrap
    depends_on:
      - kong-database
    volumes:
      - ./kong_data:/app/logs

  konga:
    image: pantsel/konga
    container_name: konga
    restart: unless-stopped
    networks:
      - subred_fcv_04  
    ports:
      - "1337:1337"
    depends_on:
      - kong-gateway
    volumes:
      - ./konga:/app/kongadata

volumes:
  kong_data:
  kong_db:
  konga:

networks:
  subred_fcv_01:
    external: true
  subred_fcv_04:
    external: true
  subred_fcv_03:
    external: true
    
```

**Comment by teneous** [comment]
I have the same issue, if I use this config, it works well .
```  
kong:
    image: kong:latest
    ports:
      - "8000:8000"   # Proxy Port 
      - "8001:8001"  # Admin API
      - "8002:8002"   # Admin WEB
      - "8444:8444"   # SSL WEB
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
      KONG_ADMIN_GUI_PATH: '/'
      KONG_ADMIN_GUI_URL: http://localhost:8002/manager
      KONG_PROXY_ACCESS_LOG: /var/log/kong/access.log
      KONG_PROXY_ERROR_LOG: /var/log/kong/error.log
      KONG_ADMIN_ACCESS_LOG: /var/log/kong/admin_access.log
      KONG_ADMIN_ERROR_LOG: /var/log/kong/admin_error.log

```
if I change 8002 to 18002, the admin page won't show any data.
```
  kong:
    image: kong:latest
    ports:
      - "18000:8000"   # Proxy Port 
      - "18001:8001"  # Admin API
      - "18002:8002"   # Admin WEB
      - "18444:8444"   # SSL WEB
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
      KONG_ADMIN_GUI_PATH: '/'
      KONG_ADMIN_GUI_URL: http://localhost:8002/manager
      KONG_PROXY_ACCESS_LOG: /var/log/kong/access.log
      KONG_PROXY_ERROR_LOG: /var/log/kong/error.log
      KONG_ADMIN_ACCESS_LOG: /var/log/kong/admin_access.log
      KONG_ADMIN_ERROR_LOG: /var/log/kong/admin_error.log
```
<img width="1240" alt="image" src="https://github.com/user-attachments/assets/6292f274-a5b4-47e5-9ca9-665ac1977f1e">

**Comment by teneous** [comment]
> I have the same issue, if I use this config, it works well .
> 
> ```
> kong:
>     image: kong:latest
>     ports:
>       - "8000:8000"   # Proxy Port 
>       - "8001:8001"  # Admin API
>       - "8002:8002"   # Admin WEB
>       - "8444:8444"   # SSL WEB
>     environment:
>       KONG_DATABASE: postgres
>       KONG_PG_HOST: kong-database
>       KONG_PG_USER: kong
>       KONG_PG_PASSWORD: kong
>       KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
>       KONG_ADMIN_GUI_PATH: '/'
>       KONG_ADMIN_GUI_URL: http://localhost:8002/manager
>       KONG_PROXY_ACCESS_LOG: /var/log/kong/access.log
>       KONG_PROXY_ERROR_LOG: /var/log/kong/error.log
>       KONG_ADMIN_ACCESS_LOG: /var/log/kong/admin_access.log
>       KONG_ADMIN_ERROR_LOG: /var/log/kong/admin_error.log
> ```
> 
> if I change 8002 to 18002, the admin page won't show any data.
> 
> ```
>   kong:
>     image: kong:latest
>     ports:
>       - "18000:8000"   # Proxy Port 
>       - "18001:8001"  # Admin API
>       - "18002:8002"   # Admin WEB
>       - "18444:8444"   # SSL WEB
>     environment:
>       KONG_DATABASE: postgres
>       KONG_PG_HOST: kong-database
>       KONG_PG_USER: kong
>       KONG_PG_PASSWORD: kong
>       KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
>       KONG_ADMIN_GUI_PATH: '/'
>       KONG_ADMIN_GUI_URL: http://localhost:8002/manager
>       KONG_PROXY_ACCESS_LOG: /var/log/kong/access.log
>       KONG_PROXY_ERROR_LOG: /var/log/kong/error.log
>       KONG_ADMIN_ACCESS_LOG: /var/log/kong/admin_access.log
>       KONG_ADMIN_ERROR_LOG: /var/log/kong/admin_error.log
> ```
> 
> <img alt="image" width="1240" src="https://private-user-images.githubusercontent.com/21994254/366295413-6292f274-a5b4-47e5-9ca9-665ac1977f1e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwMzQyNjMsIm5iZiI6MTcyNjAzMzk2MywicGF0aCI6Ii8yMTk5NDI1NC8zNjYyOTU0MTMtNjI5MmYyNzQtYTViNC00N2U1LTljYTktNjY1YWMxOTc3ZjFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDA1NTI0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiNGI0NWY1ZDRmOTgxMTdkMGQ1NTRmYmE1MjRhZmU3MWJiOWFmNjhmNTcyNzMyNDY0NDE0ZDg0NmE5YzMwOTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.w9yfNGc7XMNEUiM62hltatsn_93WBdtsRVtv3uzB4Ks">

At final, I found the reason. when you wanna use another port instead of `8002` and `8001`. You have to add this line 
```
  kong:
    image: kong:latest
    ports:
      - "18000:8000"   # Proxy Port 
      - "18001:8001"  # Admin API
      - "18002:8002"   # Admin WEB
      - "18444:8444"   # SSL WEB
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
      KONG_ADMIN_GUI_PATH: '/'
      KONG_ADMIN_GUI_API_URL: http://localhost:18001  # this is very important , it helps manger to fetch data 
      KONG_ADMIN_GUI_URL: http://localhost:18002/manager  # this is to specify the access url
      KONG_PROXY_ACCESS_LOG: /var/log/kong/access.log
      KONG_PROXY_ERROR_LOG: /var/log/kong/error.log
      KONG_ADMIN_ACCESS_LOG: /var/log/kong/admin_access.log
      KONG_ADMIN_ERROR_LOG: /var/log/kong/admin_error.log
    volumes:
      - ./logs:/var/log/kong
```

check official reference at here : `https://github.com/Kong/kong/blob/master/kong.conf.default` 

<img width="630" alt="image" src="https://github.com/user-attachments/assets/eea93241-093f-4da4-b8ae-59f49fa115c1">

<img width="1003" alt="image" src="https://github.com/user-attachments/assets/65f8b4fe-f373-47a7-b627-3641d4225b3f">
