### ISSUE TITLE
Kong with external Postgre

### ISSUE THREAD

**Issue by maestrofx** [Kong/docker-kong#76]
Hi there,

I've tried to connect Kong to external DB (say it's in RDS Postgre).
The scenario:
1. the only way to connect to DB via DB config read from `.env` file
1. no need to provision new container internal DB as a proxy from local to external, just connect to external DB defined in `.env`
1. no `external_hosts` connection

Any helps, please!
Thank you.
Fran

**Comment by maestrofx** [comment]
error logs:
`kong_1      | 2017-04-03T08:39:16.230398696Z Error: /usr/local/share/lua/5.1/kong/cmd/start.lua:21: [postgres error] could not get current migrations: [postgres error] connection refused
`

**Comment by lomori** [comment]
Maybe too late for you, but I just had the same problem. The issue was that in my case Postgres was being started immediately before Kong and it needed a few seconds to become available. So, make sure your Postgres is running and that the connection parameters are correct.

**Comment by abdulgaffarabu** [comment]
**root@slave3:~#** _sudo kong start -c /etc/kong/kong.conf_ 
ulimit is currently set to "1024". For better performance set it to at least "4096" using "ulimit -n"
Error: /usr/local/share/lua/5.1/kong/cmd/start.lua:21: [postgres error] could not get current migrations: [postgres error] connection refused

**Comment by liyuntao** [comment]
You should set password in progres and kong. There's a lack of env_var `KONG_PG_PASSWORD` in official user guide.

Here is my compose file. It works.

```yaml
version: '2'
services:
  kong-database:
    image: postgres:9.4
    container_name: kong-database
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: kong
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: your_pwd

  kong:
    image: kong:latest
    restart: always
    links:
      - kong-database:kong-database
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 7946:7946
      - 7946:7946/udp
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_PASSWORD=your_pwd
```
