### ISSUE TITLE
Docker-compose upstream returning 502 Invalid Response

### ISSUE THREAD

**Issue by vpsouza** [Kong/docker-kong#79]
Guys, I'm in trouble to run kong locally with docker-compose, my upstream server can register itself on kong admin but when I try to call the upstream through Kong I receive a 502 Bad Gateway.

base-api-gateway.yml file:
 
```
version: '2'
services:
  kong-db:
    image: postgres:alpine
    volumes:
        - ./kong-db-vol:/var/lib/postgresql
    environment:
        - POSTGRES_USER=kong
        - POSTGRES_DB=kong
  kong:
    build: ./kong
    restart: always
    mem_limit: 128m
    ports:
      - "8000:8000"
      - 8443
      - "8001:8001"
    expose:
      - 7946
      - 7946/udp
      - 8000
      - 8001
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-db
      - VIRTUAL_HOST=api.easyapps.local
      - VIRTUAL_PORT=8000 
```
 
Docker-Compose File:

```
version: '2'
services:
    easyauth:
        extends:
            file: ./easyauth/base-containers.yml
            service: easyauth-base
        ports:
            - "8085:8080"
        environment:
            - VIRTUAL_PORT=8085
            - NODE_ENV=development
            - API_GATEWAY_HOST=kong:8001
            - SERVICE_WEB_HOST=platform.easyapps.local
            - SERVICE_UPSTREAM_URL=http://localhost:8085/api/version
        depends_on:
          - easyauth-db
          - kong-db
          - kong
        command: dockerize -wait tcp://easyauth-db:5432 -wait tcp://kong-db:5432 -wait http://kong:8001 -timeout 90s npm start
    easyauth-db:
        extends:
            file: ./easyauth/base-containers.yml
            service: easyauth-db-base
    kong-db:
        extends:
            file: ./base-api-gateway.yml
            service: kong-db
    kong:
        extends:
            file: ./base-api-gateway.yml
            service: kong
        depends_on:
        - kong-db
    nginx:
        image: jwilder/nginx-proxy
        volumes:
            - "/var/run/docker.sock:/tmp/docker.sock"
        ports:
            - "80:80"
```

Request: 

> POST  http://localhost:8001/apis?name=easyauth&uris=/easyauth&upstream_url=http://localhost:8085/api/version

Response from Kong: 

> { http_if_terminated: true,
> easyauth_1     |   id: '88201e10-da71-420a-8a4a-0e8e9d61a354',
> easyauth_1     |   retries: 5,
> easyauth_1     |   preserve_host: false,
> easyauth_1     |   created_at: 1493263729000,
> easyauth_1     |   upstream_connect_timeout: 60000,
> easyauth_1     |   upstream_url: 'http://localhost:8085/api/version',
> easyauth_1     |   upstream_read_timeout: 60000,
> easyauth_1     |   https_only: false,
> easyauth_1     |   upstream_send_timeout: 60000,
> easyauth_1     |   strip_uri: true,
> easyauth_1     |   name: 'easyauth',
> easyauth_1     |   uris: [ '/easyauth' ] }

When I try the request: http://localhost:8000/easyauth I receive 502 Bad Gateway - An invalid response was received from the upstream server

Anybody can help?
